name: flutter_module
description: ecift client flutter module.

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  webview_flutter: ^4.4.2
  flutter_localizations:
    sdk: flutter
  intl: any
  logger: ^2.0.2+1
  device_info_plus: ^9.1.0
  firebase_crashlytics: ^3.4.4
  http: ^1.1.0
  native_shared_preferences: ^2.0.9
  flutter_chat_ui: ^1.6.10
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  bubble: ^1.2.1
  json_annotation: ^4.8.1
  flutter_chat_types: ^3.6.2
  android_intent_plus: ^4.0.3
  platform: ^3.1.3
  firebase_core: ^2.25.2
  empty_widget: ^0.0.5
  dummycastle: ^1.2.0
  synchronized: ^3.1.0+1
  flutter_emoji: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  generate: true

  module:
    androidX: true
    androidPackage: com.ecift.client.flutter_module
    iosBundleIdentifier: com.ecift.client.flutterModule
